//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentReg.Dal.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentRegEntities : DbContext
    {
        public StudentRegEntities()
            : base("name=StudentRegEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ASSIGNMENT> TBL_ASSIGNMENT { get; set; }
        public virtual DbSet<TBL_EXAM> TBL_EXAM { get; set; }
        public virtual DbSet<TBL_EXAM_RESULT> TBL_EXAM_RESULT { get; set; }
        public virtual DbSet<TBL_STAFF_ATTENDANCE> TBL_STAFF_ATTENDANCE { get; set; }
        public virtual DbSet<TBL_STUDENT> TBL_STUDENT { get; set; }
        public virtual DbSet<TBL_STUDENT_ATTENDANCE> TBL_STUDENT_ATTENDANCE { get; set; }
        public virtual DbSet<TBL_SUBJECT> TBL_SUBJECT { get; set; }
        public virtual DbSet<TBL_SYSUSER> TBL_SYSUSER { get; set; }
        public virtual DbSet<TBL_TEACHER> TBL_TEACHER { get; set; }
        public virtual DbSet<TBL_ASSINGMENT_RESULT> TBL_ASSINGMENT_RESULT { get; set; }
    }
}
