//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentReg.Dal.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STUDENT_ATTENDANCE
    {
        public long Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AttendanceStatus { get; set; }
    
        public virtual TBL_STUDENT TBL_STUDENT { get; set; }
    }
}
