//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentReg.Dal.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEACHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TEACHER()
        {
            this.TBL_STAFF_ATTENDANCE = new HashSet<TBL_STAFF_ATTENDANCE>();
        }
    
        public int Id { get; set; }
        public string RegNo { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string NIC { get; set; }
        public Nullable<int> Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STAFF_ATTENDANCE> TBL_STAFF_ATTENDANCE { get; set; }
    }
}
